# Generated by Django 2.2 on 2019-04-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='code',
        ),
    ]
