# Generated by Django 2.2 on 2019-04-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_version_date_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
    ]
