# Generated by Django 2.2 on 2019-04-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='code',
            field=models.CharField(default='CKP', max_length=255),
        ),
    ]
